add slack notifs
Signed-off-by: Josh Dolitsky <josh@dolit.ski>

diff --git a/.github/workflows/rumble-image-publish.yml b/.github/workflows/rumble-image-publish.yml
--- a/.github/workflows/rumble-image-publish.yml
+++ b/.github/workflows/rumble-image-publish.yml
@@ -20,6 +20,9 @@ jobs:
       packages: write
       id-token: write # needed for GitHub OIDC Token **not production ready**
     steps:
+      - name: kill me
+        run: |
+          exit 1
       - name: Checkout source code
         uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
       - name: Install Cosign
@@ -55,3 +58,13 @@ jobs:
               -invocation-event-id "${{ github.run_id }}" \
               -invocation-builder-id "${{ github.workflow }}"
           done
+
+      # Slack notification if build failing
+      - uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
+        if: failure()
+        id: slack
+        with:
+          payload: '{"text": "[rumble-image-publish] failed: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
